// <auto-generated />
using System;
using GestionPasantias.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionPasantias.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414220627_UpdateConvenioEntity")]
    partial class UpdateConvenioEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UniversidadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UniversidadId");

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.ChatParticipante", b =>
                {
                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ChatId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatParticipante");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Convenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEstudiante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUniversidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PasantiaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PasantiaId")
                        .IsUnique();

                    b.ToTable("Convenios");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.EstadoPostulacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadosPostulacion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "PendienteTutor"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "AprobadaTutor"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "RechazadaTutor"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "AprobadaSupervisor"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "RechazadaSupervisor"
                        });
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<string>("Martricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Evaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PasantiaId")
                        .HasColumnType("int");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PasantiaId")
                        .IsUnique();

                    b.HasIndex("SupervisorId");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Pasantia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostulacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostulacionId")
                        .IsUnique();

                    b.ToTable("Pasantias");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Postulacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoPostulacionId")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPostulacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("VacanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoPostulacionId");

                    b.HasIndex("VacanteId");

                    b.HasIndex("EstudianteId", "VacanteId")
                        .IsUnique();

                    b.ToTable("Postulaciones");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Nombre = "Estudiante"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Tutor"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Supervisor"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Empresa"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Universidad"
                        });
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Supervisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Supervisores");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UniversidadId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UniversidadId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Universidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Universidades");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Vacante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Vacantes");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Carrera", b =>
                {
                    b.HasOne("GestionPasantias.Domain.Entities.Universidad", "Universidad")
                        .WithMany("Carreras")
                        .HasForeignKey("UniversidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Universidad");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.ChatParticipante", b =>
                {
                    b.HasOne("GestionPasantias.Domain.Entities.Chat", "Chat")
                        .WithMany("Participantes")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionPasantias.Domain.Entities.User", "User")
                        .WithMany("ChatParticipantes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Convenio", b =>
                {
                    b.HasOne("GestionPasantias.Domain.Entities.Pasantia", "Pasantia")
                        .WithOne("Convenio")
                        .HasForeignKey("GestionPasantias.Domain.Entities.Convenio", "PasantiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pasantia");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Empresa", b =>
                {
                    b.HasOne("GestionPasantias.Domain.Entities.User", "User")
                        .WithOne("Empresa")
                        .HasForeignKey("GestionPasantias.Domain.Entities.Empresa", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Estudiante", b =>
                {
                    b.HasOne("GestionPasantias.Domain.Entities.Carrera", "Carrera")
                        .WithMany("Estudiantes")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionPasantias.Domain.Entities.User", "User")
                        .WithOne("Estudiante")
                        .HasForeignKey("GestionPasantias.Domain.Entities.Estudiante", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Evaluacion", b =>
                {
                    b.HasOne("GestionPasantias.Domain.Entities.Pasantia", "Pasantia")
                        .WithOne("Evaluacion")
                        .HasForeignKey("GestionPasantias.Domain.Entities.Evaluacion", "PasantiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionPasantias.Domain.Entities.Supervisor", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pasantia");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Mensaje", b =>
                {
                    b.HasOne("GestionPasantias.Domain.Entities.Chat", "Chat")
                        .WithMany("Mensajes")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionPasantias.Domain.Entities.User", "User")
                        .WithMany("MensajesEnviados")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Pasantia", b =>
                {
                    b.HasOne("GestionPasantias.Domain.Entities.Postulacion", "Postulacion")
                        .WithOne("Pasantia")
                        .HasForeignKey("GestionPasantias.Domain.Entities.Pasantia", "PostulacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Postulacion");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Postulacion", b =>
                {
                    b.HasOne("GestionPasantias.Domain.Entities.EstadoPostulacion", "EstadoPostulacion")
                        .WithMany("Postulaciones")
                        .HasForeignKey("EstadoPostulacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionPasantias.Domain.Entities.Estudiante", "Estudiante")
                        .WithMany("Postulaciones")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionPasantias.Domain.Entities.Vacante", "Vacante")
                        .WithMany("Postulaciones")
                        .HasForeignKey("VacanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoPostulacion");

                    b.Navigation("Estudiante");

                    b.Navigation("Vacante");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Supervisor", b =>
                {
                    b.HasOne("GestionPasantias.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Supervisores")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionPasantias.Domain.Entities.User", "User")
                        .WithOne("Supervisor")
                        .HasForeignKey("GestionPasantias.Domain.Entities.Supervisor", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Tutor", b =>
                {
                    b.HasOne("GestionPasantias.Domain.Entities.Universidad", "Universidad")
                        .WithMany("Tutores")
                        .HasForeignKey("UniversidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionPasantias.Domain.Entities.User", "User")
                        .WithOne("Tutor")
                        .HasForeignKey("GestionPasantias.Domain.Entities.Tutor", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Universidad");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Universidad", b =>
                {
                    b.HasOne("GestionPasantias.Domain.Entities.User", "User")
                        .WithOne("Universidad")
                        .HasForeignKey("GestionPasantias.Domain.Entities.Universidad", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.User", b =>
                {
                    b.HasOne("GestionPasantias.Domain.Entities.Rol", "Rol")
                        .WithMany("Users")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Vacante", b =>
                {
                    b.HasOne("GestionPasantias.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Vacantes")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionPasantias.Domain.Entities.Supervisor", "Supervisor")
                        .WithMany("Vacantes")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Carrera", b =>
                {
                    b.Navigation("Estudiantes");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Chat", b =>
                {
                    b.Navigation("Mensajes");

                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Supervisores");

                    b.Navigation("Vacantes");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.EstadoPostulacion", b =>
                {
                    b.Navigation("Postulaciones");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Estudiante", b =>
                {
                    b.Navigation("Postulaciones");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Pasantia", b =>
                {
                    b.Navigation("Convenio");

                    b.Navigation("Evaluacion");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Postulacion", b =>
                {
                    b.Navigation("Pasantia");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Supervisor", b =>
                {
                    b.Navigation("Vacantes");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Universidad", b =>
                {
                    b.Navigation("Carreras");

                    b.Navigation("Tutores");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.User", b =>
                {
                    b.Navigation("ChatParticipantes");

                    b.Navigation("Empresa");

                    b.Navigation("Estudiante");

                    b.Navigation("MensajesEnviados");

                    b.Navigation("Supervisor");

                    b.Navigation("Tutor");

                    b.Navigation("Universidad");
                });

            modelBuilder.Entity("GestionPasantias.Domain.Entities.Vacante", b =>
                {
                    b.Navigation("Postulaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
